### ISSUE TITLE
Link for source file broken

### ISSUE THREAD

**Issue by farishaddad** [Azure/LearnAI-Cognitive-Search#1]
On the Environment Creation page, in Step two the "Download the sample data" link drops you in a temp One drive folder that does not contain this file

**Comment by Rodrigossz** [comment]
The link is working for 2 other people. It opens an OneDrive folder, with 19 files. I uploaded the dataset to the Github just in case. But to download it, they will need to download the all repo. The OneDrive is public and has the download button.
